#ifndef LGAMEOBJECT_TYPES_H_
#define LGAMEOBJECT_TYPES_H_

enum lgameobject_type {
	LEMPTY_GAMEOBJECT_TYPE,
	LINPUTBOX_TYPE,
	LBUTTON_TYPE,
	LHNAVBAR_TYPE,
	LTEXT_TYPE,
	LTEXT_BUTTON_TYPE
};

#endif /* !LGAMEOBJECT_TYPES_H_ */